[package]
name = "rust_typeclass_nonsense"
version = "0.1.0"
authors = ["Lily Lin <arcticfox517@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
